base/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

dtmult/base/urls.py
from django.urls import path

from dtmult.base.views import home

app_name = 'base'
urlpatterns = [
    path('', home, name='home')
]

dtmult/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('dtmult.base.urls')),
    path('propriedades/', include('dtmult.propriedades.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns.append(
        path('__debug__/', include(debug_toolbar.urls))
    )

dtmult/base/models.py
from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
from django.contrib.auth.models import PermissionsMixin
from django.core.mail import send_mail
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from django.db import models


class UserManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        """
        Create and save a user with the given username, email, and password.
        """
        if not email:
            raise ValueError('The given email must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email=None, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(email, password, **extra_fields)


class User(AbstractBaseUser, PermissionsMixin):
    """
    App base user class

    Email e password required fields
    """

    first_name = models.CharField(_('first name'), max_length=30, blank=True)
    email = models.EmailField(_('email address'), unique=True)
    is_staff = models.BooleanField(
        _('staff status'),
        default=False,
        help_text=_('Designates whether the user can log into this admin site.'),
    )
    is_active = models.BooleanField(
        _('active'),
        default=True,
        help_text=_(
            'Designates whether this user should be treated as active. '
            'Unselect this instead of deleting accounts.'
        ),
    )
    date_joined = models.DateTimeField(_('date joined'), default=timezone.now)

    objects = UserManager()

    EMAIL_FIELD = 'email'
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')

    def clean(self):
        super().clean()
        self.email = self.__class__.objects.normalize_email(self.email)

    def get_full_name(self):
        """
        Return the first_name plus the last_name, with a space in between.
        """
        full_name = '%s' % (self.first_name)
        return full_name.strip()

    def get_short_name(self):
        """Return the short name for the user."""
        return self.first_name

    def email_user(self, subject, message, from_email=None, **kwargs):
        """Send an email to this user."""
        send_mail(subject, message, from_email, [self.email], **kwargs)


class Profile(models.Model):
    PROP_VENDEDOR = 1
    PROP_COMPRADOR = 2
    LOCATARIO = 3
    ROLE_CHOICES = (
        (PROP_VENDEDOR, 'Proprietário Vendedor'),
        (PROP_COMPRADOR, 'Proprietário comprador'),
        (LOCATARIO, 'Locatário'),
    )
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    # endereco = models.CharField(max_length=10,)
    # numero = models.CharField(max_length=10, blank=True, null=True)
    # complemento = models.CharField(max_length=30, blank=True, null=True)
    # bairro = models.CharField(max_length=32, null=True)
    # cep = models.CharField(max_length=8, blank=True)
    data_nascimento = models.DateField(null=True, blank=True)
    role = models.PositiveSmallIntegerField(choices=ROLE_CHOICES, null=True, blank=True)

    class Meta:
        verbose_name = 'profile'
        verbose_name_plural = 'profiles'

    def __str__(self):
        return self.user.email


@receiver(post_save, sender=User)
def create_or_update_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)
    instance.profile.save()

dtmult/base/views.py
from django.shortcuts import render


def home(request):
    return render(request, 'base/home.html', {})

dtmult/base/templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>{% block title %}Dutty{% endblock title %}</title>

    <meta name="description" content="{% block description %}TotaoLabs{% endblock description %}">
    <meta name="author" content="TotaoLabs!">

    <link href="{% static '/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static '/css/style.css' %}" rel="stylesheet">
    <script src="{% static '/js/jquery.min.js' %}"></script>
    <script src="{% static '/js/bootstrap.min.js' %}"></script>
    <script src="{% static '/js/scripts.js' %}"></script>
</head>
<body>

<nav class="navbar navbar-expand-lg navbar-dark navbar-custom" style="background-color: #253b50;">

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="navbar-toggler-icon"></span>
    </button>
    <a class="navbar-brand" href="{% url 'base:home' %}">Home</a>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="navbar-nav">
{#            <li class="nav-item active">#}
{#                <a class="nav-link" href="#">Link <span class="sr-only">(current)</span></a>#}
{#            </li>#}
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink"
                   data-toggle="dropdown">Tipos de multipropriedades</a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
                    {% for tipo_multipropriedade in TIPOMULTIPROPRIEDADE %}
                     <a class="dropdown-item" href="{{tipo_multipropriedade.get_absolute_url}}">{{tipo_multipropriedade.nome}}</a>
                    <div class="dropdown-divider"></div>
                    {% endfor %}
                </div>
            </li>
        </ul>
    </div>
</nav>
{% block body %}{% endblock body %}

<footer class="main-footer mt-5 pt-4 text-light">
    <div class="container">
        <div class="row">
            <div class="col">
                <h3>Entre em Contato</h3>
                <address>
                    +559999983236
                    </br>
                    <a href="mailto:dutty@dutty.com" class="text-light">dutty@dutty.com</a>
                </address>
            </div>

        </div>
    </div>
    <div class="rights">
        <div class="container">
            <div class="row">
                <div class="col">
                    {% now 'Y' %} Dutty. Todos os direitos reservados!
                </div>
            </div>
        </div>
    </div>
</footer>

</body>
</html>

dtmult/base/templates/base/home.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %}Dutty - Home{% endblock title %}
{% block body %}
<div class="jumbotron">
    <h2>
        Dutty, multipropriedade!
    </h2>
    <p>
        A vida é agora, viva mais com a multipropriedade"
    </p>
    <p>
        <a class="btn btn-primary btn-large" href="#">Saiba mais</a>
    </p>
</div>
<!-- MAIL CHIMP -->
<h4 class="mt-4">Subscribe</h4>
<form action="https://gmail.us4.list-manage.com/subscribe/post?u=4c9573a39fabd6c508a19c4f7&amp;id=ae86c278f4"
      method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form"
      class="form-row align-items-center" target="_blank" novalidate>
    <div class="form-row align-items-center">
        <div class="col-auto">
            <label class="sr-only" for="mce-EMAIL">Email</label>
            <input type="email" value="" name="EMAIL" class="form-control required" id="mce-EMAIL"
                   placeholder="exemplo@email.com">
        </div>
        <div class="col-auto">
            <label class="sr-only" for="mce-FNAME">Email</label>
            <input type="text" value="" name="FNAME" class="form-control" id="mce-FNAME">
        </div>
        <div style="position: absolute; left: -5000px;" aria-hidden="true"><input type="text"
                                                                                      name="b_4c9573a39fabd6c508a19c4f7_ae86c278f4"
                                                                                      tabindex="-1" value=""></div>
        <div class="col-auto">
            <input type="submit" value="Subscribe" name="subscribe" id="mc-embedded-subscribe"
                                      class="btn btn-primary"></div>
        </div>

    </div>
</form>
{% endblock body %}